version: '3.5'

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - ./config.json:/etc/v2ray/config.json
      - ./log/v2ray:/var/log/v2ray
      - vhost:/vhost
      - ./vv.maki0419.com_location:/vhost/your.domain.com_location
    expose:
      - "8002"
    restart: always
    env_file:
      - app.env
    networks:
      - proxy-tier

volumes:
  vhost:
    external: true
    name: docker-nextcloud_vhost
networks:
  proxy-tier:
    external: true
    name: docker-nextcloud_proxy-tier
