version: '3.5'

services:
  v2ray:
    image: v2fly/v2fly-core
    container_name: v2ray
    volumes:
      - ./config.json:/config:ro
      - ./location:/location:ro
      - ./log/v2ray:/var/log/v2ray
      - vhost:/vhost
    expose:
      - "8002"
    restart: always
    command: sh -c "sed 's/UUID/${UUID}/g' /location | sed 's/DOMAIN/${DOMAIN}/g' > /vhost/${DOMAIN}_location && sed 's/UUID/${UUID}/g' /config > /config.json && v2ray -config=/config.json"
    environment:
      - DOMAIN
      - UUID
      - VIRTUAL_HOST=${DOMAIN}
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
    networks:
      - proxy-tier

volumes:
  vhost:
    external: true
    name: docker-reverseproxy_vhost
networks:
  proxy-tier:
    external: true
    name: proxy-tier
